### ISSUE TITLE
Label incorrect

### ISSUE THREAD

**Issue by dylanosaur** [MatMan02/Genius-or-Not#1]
Tested on my face and gave wrong result.

**Comment by MatMan02** [comment]
LOL what did you get? (think also that I tried it and it gave me 98% NON genius. And I created it.)

**Comment by dylanosaur** [comment]
My IQ is over 9000. I expected maximum genius likelihood.

**Comment by dylanosaur** [comment]
This world is not ready for my genius. Closing issue.

**Comment by MatMan02** [comment]
LoL
